import { AuditReport, ManagementReport, ReportComparison } from "./api";

export const demoReport: AuditReport = {
  id: "demo-report-2026-06",
  file_name: "demo-retail-report-june.xlsx",
  status: "completed",
  risk_score: 58,
  risk_level: "high",
  total_findings: 6,
  summary:
    "Найдено 6 замечаний. Критичных: 1, высокого риска: 3, fraud-сигналов: 3. Главные зоны внимания: итоговая строка, премии выше лимита, крупные скидки и возвраты в конце месяца.",
  recommendations: [
    "Сначала исправьте итоговую строку: расхождение влияет на финансовый результат месяца.",
    "Проверьте премии выше лимита и запросите основание начисления.",
    "Сверьте крупные скидки и возвраты с POS-системой и первичными документами.",
    "После исправлений загрузите отчет повторно и сохраните PDF для закрытия месяца.",
  ],
  workbook_profile: {
    quality_score: 42,
    sheet_count: 3,
    metric_totals: {
      sales: 4850000,
      profit: 690000,
      salary: 920000,
      bonus: 310000,
      expense: 740000,
      discount: 265000,
      return: 180000,
    },
    sheets: [
      {
        name: "Sales",
        rows_sampled: 80,
        columns_sampled: 9,
        non_empty_cells_sampled: 612,
        numeric_columns_sampled: 6,
        metric_totals: { sales: 4850000, discount: 265000, return: 180000 },
      },
      {
        name: "Payroll",
        rows_sampled: 42,
        columns_sampled: 6,
        non_empty_cells_sampled: 211,
        numeric_columns_sampled: 3,
        metric_totals: { salary: 920000, bonus: 310000 },
      },
      {
        name: "Expenses",
        rows_sampled: 55,
        columns_sampled: 5,
        non_empty_cells_sampled: 247,
        numeric_columns_sampled: 2,
        metric_totals: { expense: 740000, profit: 690000 },
      },
    ],
  },
  created_at: "2026-06-16T09:00:00.000Z",
  findings: [
    {
      code: "TOTAL_MISMATCH",
      severity: "critical",
      sheet_name: "Sales",
      cell: "G82",
      row_number: 82,
      column_name: "Итого",
      title: "Итог не сходится",
      description: "Итог 4 850 000 не совпадает с суммой строк выше 4 720 000.",
      suggested_fix: "Проверьте диапазон формулы и строки, которые входят в итог.",
      evidence: { expected: 4850000, calculated: 4720000, difference: 130000 },
    },
    {
      code: "BONUS_LIMIT_EXCEEDED",
      severity: "high",
      sheet_name: "Payroll",
      cell: null,
      row_number: 18,
      column_name: "Премия",
      title: "Премия выше лимита",
      description: "Премия 95 000 превышает 50% зарплаты сотрудника.",
      suggested_fix: "Проверьте основание премии и согласование с бухгалтерией.",
      evidence: { salary: 150000, bonus: 95000, limit_ratio: 0.5 },
    },
    {
      code: "SUSPICIOUS_DISCOUNT",
      severity: "high",
      sheet_name: "Sales",
      cell: null,
      row_number: 37,
      column_name: "Скидка",
      title: "Подозрительно большая скидка",
      description: "Скидка 62% выглядит выше обычного лимита.",
      suggested_fix: "Проверьте разрешение на скидку и условия акции.",
      evidence: { discount: 62 },
    },
    {
      code: "MONTH_END_RETURN_SPIKE",
      severity: "high",
      sheet_name: "Sales",
      cell: null,
      row_number: 74,
      column_name: "Возврат",
      title: "Возврат перед закрытием месяца",
      description: "Крупный возврат 86 000 найден 29 числа.",
      suggested_fix: "Сверьте чек возврата и причину операции перед закрытием отчетности.",
      evidence: { return: 86000, day: 29 },
    },
    {
      code: "REQUIRED_CELL_EMPTY",
      severity: "medium",
      sheet_name: "Sales",
      cell: "B46",
      row_number: 46,
      column_name: "Сотрудник",
      title: "Пустая обязательная ячейка",
      description: "В строке 46 не указан сотрудник.",
      suggested_fix: "Заполните значение или удалите строку, если она не относится к отчету.",
      evidence: {},
    },
    {
      code: "DUPLICATE_ROW",
      severity: "low",
      sheet_name: "Expenses",
      cell: null,
      row_number: 22,
      column_name: null,
      title: "Дубликат строки",
      description: "Строка 22 полностью совпадает с другой строкой на листе.",
      suggested_fix: "Проверьте, не была ли операция случайно скопирована дважды.",
      evidence: {},
    },
  ],
};

export const demoComparison: ReportComparison = {
  current_report_id: demoReport.id,
  previous_report_id: "demo-report-2026-05",
  summary:
    "Относительно прошлого месяца риск вырос: увеличились возвраты, скидки и количество замечаний высокого риска.",
  metrics: [
    { metric_name: "risk_score", current_value: 58, previous_value: 31, delta_value: 27, delta_percent: 87.1, severity: "high" },
    { metric_name: "total_findings", current_value: 6, previous_value: 3, delta_value: 3, delta_percent: 100, severity: "high" },
    { metric_name: "sales", current_value: 4850000, previous_value: 5020000, delta_value: -170000, delta_percent: -3.39, severity: "info" },
    { metric_name: "profit", current_value: 690000, previous_value: 810000, delta_value: -120000, delta_percent: -14.81, severity: "low" },
    { metric_name: "bonus", current_value: 310000, previous_value: 205000, delta_value: 105000, delta_percent: 51.22, severity: "high" },
    { metric_name: "expense", current_value: 740000, previous_value: 610000, delta_value: 130000, delta_percent: 21.31, severity: "low" },
  ],
};

export const demoManagementReport: ManagementReport = {
  report_id: demoReport.id,
  title: "Отчет для руководства: demo-retail-report-june.xlsx",
  text:
    "За июнь отчет требует проверки перед закрытием месяца. Риск высокий из-за расхождения итоговой строки, премии выше лимита, крупной скидки и возврата в конце месяца. Рекомендуется сначала сверить итог продаж, затем проверить основания премий и документы по скидкам/возвратам.",
  highlights: [
    "Оценка качества отчета: 42/100.",
    "Найдено замечаний: 6.",
    "Продажи: 4 850 000.",
    "Прибыль: 690 000.",
    "Премии: 310 000.",
    "Расходы: 740 000.",
  ],
};
